### ISSUE TITLE
Why writing yet another unit test framework

### ISSUE THREAD

**Issue by tgy** [NumScale/stf#16]
Why writing yet another unit test framework? What is `stf` going te bring that other frameworks aren't?

**Comment by jfalcou** [comment]
Nothing in particular. We had specific needs in term of testing IEEE values and array like structure so we build STF for that. It's open becasue we had a bunch of people wanting to use it. Not pressuring anybody to use it but we thought it may be of interest to have this implementation laying around.

Feel free to use something else if you don't fit into the use cases we wanted to provide. 

Best regards

**Comment by tgy** [comment]
Alright, I was just wondering what it was bringing and it wasn't detailed in the README. Thanks for answering Joel!

**Comment by jfalcou** [comment]
I confess the readme.md is a bit dry. Martin Moene's description is actually better : "Catch/lest-inspired with an emphasis on floating point precision testing."

**Comment by jfalcou** [comment]
I added some meat ot the readme, tell me if it makes sence now

**Comment by tgy** [comment]
Yes, it makes sense :) I submitted https://github.com/NumScale/stf/pull/17 to fix some typos.
