### ISSUE TITLE
Add STF_SKIP check

### ISSUE THREAD

**Issue by xaxousis** [NumScale/stf#27]
This would allow warning the user that a check was not run because some preconditions were not met.

Example case:
  - A function must return a vector containing 5 values.
  - Each value must be checked individually
The 2nd step must check that the value exists (i.e. the first check failed or not). `STF_SKIP` would point out that a check that should have been run wasn't.

**Comment by jfalcou** [comment]
Testing arrays/vectors using STF_ALL_* is doign this already (check size nd dont do anything more if they're ot the same).

Do you want that for more situation ?

**Comment by xaxousis** [comment]
```cpp
auto object = do_something_not_trivial();

STF_EXPECT(object.this_will_not_segfault());
if(object.this_will_not_segfault()) {
  STF_EQUAL(object.some_value(), reference_value);
} else {
  STF_SKIP("Reference test was skipped because object was not left in a valid state.");
  // At the moment, this can be done with STF_FAIL, SKIP would only add
  // context information as to why the test was not run.
}
```

The main interest is that the number of tests that are run is the same whether the first test is valid or not.

I'm closing this as STF_FAIL already provides a solution when an explicit fail message is given.
